Fix Typescript Arrow Consts needing using the filename
UXPin/uxpin-merge-tools pull request #209
Opened 2020-10-26 03:50 UTC by jrwpatterson

This PR should fix the fact that the latest release of Arrow names needs the filenames to be in ProperCase because the arrow-function implementation is a child of the actual component. This means that in getComponentName it was falling back to the filename and dumping components such as `import simple-select from '../src/components/simple-select.tsx` in the components.js file in the .uxpin-merge

I don't think it will affect any other way of importing when using typescript.

2020-10-28 14:29 UTC, itsderek23 commented
Thanks @jrwpatterson ! We'll review and update.

2020-10-29 01:38 UTC, vados-xenon requested changes
Thanks for submitting this PR!  A few comments but nothing major.

2020-10-29 01:38 UTC, vados-xenon commented on packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/getComponentName.ts
> +import * as ts from 'typescript'
Would you mind importing just `isArrowFunction`, `ArrowFunction`, and `Identifier` here?

```suggestion
import { ArrowFunction, isArrowFunction, Identifier } from 'typescript';
```

2020-10-29 01:38 UTC, vados-xenon commented on packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/getComponentName.ts
> +  if(component.name) {
Small style fix, there's a space missing here

```suggestion
  if (component.name) {
```

2020-10-29 01:38 UTC, vados-xenon commented on packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/getComponentName.ts
> +  if (ts.isArrowFunction(component) && component.parent && (component.parent as ts.ArrowFunction).name){
A comment on this case would be great

```suggestion
  // Support named arrow functions and use the component parent's name.
  // https://github.com/UXPin/uxpin-merge-tools/issues/208
  if (ts.isArrowFunction(component) && component.parent && "name" in component.parent && (component.parent as ts.ArrowFunction).name) {
```

I also think that check could be slightly safer so I added that too

2020-10-29 04:20 UTC, jrwpatterson commented
@vados-xenon I have accepted your comments thank you

2020-10-29 06:13 UTC, vados-xenon approved these changes

2020-10-30 08:40 UTC, matthewchigira approved these changes
Thank you very much for your PR @jrwpatterson 

Looks good to me :+1:

2020-10-30 08:42 UTC, merged