Ability to publish package from branch for development and test purpose
UXPin/uxpin-merge-tools pull request #234
Opened 2021-02-05 04:47 UTC by naohiro-t

2021-02-05 06:28 UTC, matthewchigira requested changes

2021-02-05 06:39 UTC, naohiro-t commented on .github/bin/publish-package.sh
> +npm publish --tag "${tag}" --verbose || true
We can make always make it "dev" too! Just thought branch name is more clear which package you want :) 

> The name of the package comes from the name specified in the package.json file.
Yes, `build-utils publishprepare` will update package.json, then publish.

2021-02-05 07:31 UTC, naohiro-t commented on .github/bin/publish-package.sh
> +npm publish --tag "${tag}" --verbose || true
Changed tag to be always "dev".

2021-02-05 08:21 UTC, matthewchigira commented on .github/bin/publish-package.sh
> +npm publish --tag "${tag}" --verbose || true
Sorry for opening this again (:smile: )

Don't we just want to use `build-utils` to write the update into `package.json` file and then just publish with the tag of `dev`?

```
build-utils publishprepare --branch dev --build-num "${BUILD_NUM}"
npm publish --tag dev --verbose || true
```

2021-02-09 02:33 UTC, naohiro-t commented on .github/bin/publish-package.sh
> +npm publish --tag "${tag}" --verbose || true
My change does the same as what you described, but your way is cleaner :) So, I've updated!

2021-02-09 05:22 UTC, matthewchigira commented on .github/bin/publish-package.sh
> +npm publish --tag "${tag}" --verbose || true
Thanks! :sunglasses:

2021-02-09 05:23 UTC, matthewchigira approved these changes
LGTM :rocket:

2021-02-09 05:55 UTC, merged